.gitignore
.studiorc
go.mod
go.sum
habitat/plan.sh
main.go

This PR is creating a very basic Go binary that leverages a couple of Chef Server
APIs, such endpoints are 1) Nodes list and 2) Cookbook lists. The way this PR
is implemented is only as an example of how can we use the Go Chef library:
- https://github.com/go-chef/chef
To test this PR you need to enter a studio and then run the following
commands:
```
$ hab studio enter
[1][default:/src:0]# build
[2][default:/src:0]# source results/last_build.env
[3][default:/src:0]# hab pkg install -b -f "results/${pkg_artifact}"
[4][default:/src:0]# chef-analyze -user afiune -key afiune.pem -chef_server_url "https://chef-server-acceptance.chef.co/organizations/chef-workstation/"
Nodes:
Cookbooks:
```
To cross-compile this binary you can use the studio helper:
```
$ hab studio enter
[1][default:/src:0]# …
```

Create a go binary that leverages Chef Server API

---

main.go

The usage here is to enable our pipeline to check if the chef-analyze
command was built and install and runs. (Minimal check)
https://github.com/chef/chef-workstation/pull/553
```
$ chef-analyze help
Usage of chef-analyze:
-chef_server_url string
Chef Infra Server URL.
-key string
Chef Infra Server API client key.
-user string
Chef Infra Server API client username.
$ echo $?
0
```

Adds chef-analyze help / Usage()

---

.bldr.toml
.expeditor/build.habitat.yml
.expeditor/config.yml
.expeditor/verify.pipeline.yml

This PR extends the expeditor config to do the following things:
- Triggers pipeline verifications.
- Handle version bump.
- Build Habitat packages.
Closes https://github.com/chef/chef-analyze/issues/3

Extend Expeditor config/verifications

---

.bldr.toml

The `core/scaffolding-go` is not yet building packages for linux kernel2.
Logs:
```
☁ Determining latest version of core/scaffolding-go in the 'stable' channel
  | ✗✗✗
  | ✗✗✗ Package not found.
  | ✗✗✗
  | chef-analyze: WARN: Could not find a suitable installed package for 'core/scaffolding-go'
  | chef-analyze: ERROR: Resolving 'core/scaffolding-go' failed, should this be built first?
```

Do not build Hab pkg for kernel2

---

.expeditor/config.yml

I think with this we will be able to do promotions in Slack like:
```
/expeditor promote chef/chef-analyze:master VERSION
```

Enable hab pkg promotions through Expeditor

---

go.sum
main.go

This adds a simple example of a cookbook oriented report:
```
➜  bin/chef-analyze_darwin_amd64 -user "afiune" -key ~/.chef/afiune.pem -chef_server_url 'https://chef-server.example.com/organizations/chef-workstation/'
Node Name   Chef Version   OS                OS Version
bar   <nil>          <nil>             <nil>
chef-load-6   13.2.28        mac_os_x          10.14.6
chef-load-40   12.5.54        mac_os_x          10.14.6
kitchen-ubuntu   15.3.14        ubuntu            18.04
chef-load-52   13.1.0         ubuntu            18.04
chef-load-7   15.3.14        platform 14       <nil>
chef-load-9   15.3.14        ubuntu            18.04
chef-load-8   15.3.14        windows           6.3.9600
chef-load-50   15.3.14        platform 14       <nil>
chef-load-4   15.3.14        windows …
```

Adds an example report for cookbooks

---

cmd/errors.go
cmd/root.go

The cobra `OnInitialize` function will run for every single command on the
CLI, that includes the `help` command, but if a user is asking for help, we
should not throw and error, instead just print the usage 💯 
Now the user will see the following output:
```
$ chef-analyze help
Analyze your Chef inventory by generating reports to understand the effort
to upgrade to the latest version of the Chef tools, automatically fixing
violations and/or deprecations, and generating Effortless packages.
Usage:
chef-analyze [command]
Available Commands:
help        Help about any command
report      Generate reports about your Chef inventory
Flags:
-s, --chef_server_url string   Chef Infra Server URL
-k, --client_key string        Chef Infra Server API client key
-n, --client_name string       Chef …
```

Fix the chef-analyze help command

---

pkg/config/config.go

Before this change, we were using the Go core library `path` to join
filesystem paths, it worked in Unix systems but on Windows, we end up
in an infinite loop.
The fix is to use the Go core library `path/filepath`...
N/A

[bug-fix] Infinite loop on windows platforms

---

go.mod

As the Release notes say, we have to switch the version inside the `go.mod`:
>If your code uses modules and your go.mod files specifies a language version, be sure it is set to at least 1.13 to get access to these language changes. You can do this by editing the go.mod file directly, or you can run `go mod edit -go=1.13`.
https://golang.org/doc/go1.13#language

Bump Go module to 1.13

---

.buildkite/hooks/post-artifact
.expeditor/config.yml

When there is a 0% increase, it means that the change is not modifying
any code or test, let us cover that case with a nice message.
See an example of this new message below: https://github.com/chef/chef-analyze/pull/45#issuecomment-548700316
Additionally, the pipeline will show the following information message:
Finally, there is a new tag to ignore/skip the code coverage update on any PR merge,
the tag name is **"Expeditor: Skip Code Coverage"**.
N/A

Display code coverage message for 0% increase

---

Makefile

The core/scaffolding-go has a feature that, if a Go project has a
`Makefile` inside the source directory (`/src`), it will execute `make`
to build the go binary. Since I added a `Makefile`, the pipeline has
been failing for a couple of days. This change detects if we are running in
our CI pipeline, and if so, changes the default make task to build the
go binary as the scaffolding does it.
- No Issue.
- Pipeline: https://buildkite.com/chef/chef-chef-analyze-master-habitat-build
- Core Scaffolding Docs: https://github.com/habitat-sh/core-plans/tree/master/scaffolding-go#scaffolding_go_build

Fix Habitat builds

---

Makefile
README.md

It is better to make the `go-build` the default make task than adding all
the extra logic (headache) for running it differently in CI or Locally.

Make go-build the default make tasks

---

.studiorc
pkg/config/config.go
pkg/config/config_test.go
pkg/config/errors.go
pkg/config/finder.go
pkg/config/finder_test.go
pkg/featflag/example/main.go
pkg/featflag/features.go
pkg/featflag/features_test.go

In order for us to be able to turn feature flags on and off from the [Chef
Workstation App](https://github.com/chef/chef-workstation-app) we need to teach the new `config` go package to read
and merge the app config (`~/.chef-workstation/.app-managed-config.toml`)
to the user config (`~/.chef-workstation/config.toml`). Well this is the pull
request that makes it happen.
This PR includes the following enhancements:
- Two new `config` builder functions, `App()` and `User()`, these functions
will initialize a config from the application's point of view or the user's point of view.
- The previous `New()` builder function now returns a global config that
merges both, the app and user configs.
- Adds a real feature flag example located at `pkg/featflag/example`
- Create a proper log go package …

Read and Merge WS Tray App config

---

go.mod
go.sum
integration/featflag_test.go
integration/framework_test.go
main.go
vendor/github.com/chef/go-libs/featflag/features.go
vendor/github.com/chef/go-libs/featflag/lookup.go
vendor/modules.txt

Since we are still in experimental/development mode, we will make sure
users know it by blocking the execution of this binary unless the
feature flag is enabled.
Running the command with feature flag disabled:
```
$ chef-analyze
`analyze` is experimental and in development.
Temporarily enable `analyze` with the environment variable:
CHEF_FEAT_ANALYZE=true
Or, permanently by modifying $HOME/.chef-workstation/config.toml with:
[features]
analyze = true
```
Running the command with feature flag enabled:
```
$ CHEF_FEAT_ANALYZE=true chef-analyze
Analyze your Chef Infra Server artifacts to understand the effort to upgrade
your infrastructure by generating reports, automatically fixing violations
and/or deprecations, and generating Effortless packages.
Usage:
chef-analyze [command]
Available …
```

chef-analyze is in development and will be hidden

---

pkg/reporting/cookstyle.go
pkg/reporting/cookstyle_test.go

If our goal is allow for upgrades then the only cops that are 100%
required are the ChefDeprecations cops. We should skip all the others.
Perhaps a flag later on to enable all Chef cops, but this is better for
now.
Signed-off-by: Tim Smith <tsmith@chef.io>

Only check for ChefDeprecations cops in Cookstyle

---

integration/report_nodes_test.go
pkg/formatter/table.go

This change stops trying to pre-allocate most of the column widths, and
allows the tablewriter package to handle that.
It puts a soft constraint of 120 characters/ncols on each column,
but this will only be respected if the content will wrap - so it's still
possible to go beyond 120 characters.
Finally, it checks the length of the actual output and updates the
'adjust your screen size' note to include the needed size based on
content, instead of a 'recommended minimum'
Fixes #93 

Use actual table output size for warning message

---

integration/report_nodes_test.go
pkg/formatter/table.go
pkg/formatter/table_test.go

- Display the message `No nodes found to analyze.` when there are no nodes in chef infra server org.
Fixes https://github.com/chef/chef-analyze/issues/94
Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

[Nodes report] Display the message "No nodes found to analyze."   

---

.expeditor/verify.pipeline.yml
integration/credentials_test.go
integration/framework_test.go
scripts/integration_tests.ps1

Currently, if there are failures on our integration tests inside buildkite we
don't see them since they are not propagated to the job status, this PR is
the fix to catch errors and mark the pipeline red 🔴 
The reason this is happening is because Hab Studios are not propagating
the errors, the way to workaround this was to add an `Exit` statement after
the execution of the PowerShell script.

integration:(fix-test) catch errors on buildkite

---

pkg/reporting/cookstyle.go
pkg/reporting/cookstyle_test.go

Now that 5.15 is out everything in ChefCorrectness should be corrected
before upgrading chef-client releases.
Signed-off-by: Tim Smith <tsmith@chef.io>

Run the ChefCorrectness cops in Cookstyle

---

cmd/report.go
pkg/formatter/csv.go
pkg/formatter/csv_test.go
pkg/formatter/formatter_internal_test.go
pkg/formatter/table.go
pkg/formatter/table_test.go
pkg/formatter/txt.go
pkg/formatter/txt_test.go
pkg/reporting/cookbooks_test.go
pkg/reporting/nodes.go
pkg/reporting/nodes_test.go

Stores nodes report to disk.
```
$ chef-analyze report nodes
Analyzing nodes...
-- REPORT SUMMARY --
Node Name      Chef Version   Operating System    Cookbooks
-----------------+--------------+-------------------+------------
bar              -              -                           0
chef-load-6      13.2.28        mac_os_x v10.14.6           0
chef-load-40     12.5.54        mac_os_x v10.14.6           0
kitchen-ubuntu   15.3.14        ubuntu v18.04               0
chef-load-52     13.1.0         ubuntu v18.04               0
chef-load-7      15.3.14        platform 14 v               0
chef-load-9      15.3.14        ubuntu v18.04               0
chef-load-8      15.3.14        windows v6.3.9600           0
chef-load-50     15.3.14        platform 14 v               0
chef-load-4 …
```

feat:(store-reports) txt/csv nodes reports

---

pkg/formatter/csv.go
pkg/formatter/csv_test.go

I had [a card](https://github.com/chef/chef-analyze/issues/88) to convert from my old 'fancy' csv outformatter that tried to not repeat data in columns when it was the same in the row above (made data appear to cascade down and to the right). It was a dumb thing to do - thats not how CSV works. Someone already fixed this issue for me so I just added a few tests and fixed a few warnings. Thanks @afiune and @marcparadise !
Fixes https://github.com/chef/chef-analyze/issues/88

Verifying multiple rows output data in every cell

---

pkg/reporting/chef_client_test.go
pkg/reporting/client_test.go
pkg/reporting/cookbooks_test.go
pkg/reporting/cookstyle_test.go
pkg/reporting/reporting_test.go
pkg/reporting/setup_test.go

Mocking the Home directory will allow us to play safe with the `.chef`
and `.chef-workstation` directories.
Closes https://github.com/chef/chef-analyze/issues/57

unit:(tests) mock home dir as temp dir

---

pkg/reporting/cookstyle.go
pkg/reporting/cookstyle_test.go

Doing a little bit of research on cookstyle/rubocop I found an option
that will help use ignore any `.rubocop.yml` that might conflict with
the current state of things.
This is a possible solution instead of deleting the file we will ignore
it so that we do not modify the customers data just yet. We might do
that in next iteration to fix things on cookbooks/data.
N/A

cookstyle:(config) use --force-default-config

---

cmd/report.go
pkg/reporting/cookbooks.go
pkg/reporting/cookbooks_test.go

This draft PR does the following: 
- moves all IO (uincluding progress) out of the reporting package.  This now reports progress through analyzes back to the caller via a channel. 
- fixes cases where we don't always report 100% progress on completion - no more paths to exit the pipeline that don't report 
- speeds up run time on large data sets by about 10% by eliminating channel bottlenecks/conflicts
Fixes: #136

Move remaining IO out of reporting pkg

---

pkg/formatter/csv.go
pkg/formatter/csv_test.go
pkg/formatter/formatter.go
pkg/formatter/formatter_internal_test.go
pkg/formatter/table.go
pkg/formatter/txt.go
pkg/formatter/txt_test.go
pkg/reporting/cookbooks.go
pkg/reporting/cookbooks_test.go

* Sorts cookbooks by name, then version in all reports.
* Sorts nodes by name in csv and tx reports
Added new sorting function in formater that is called by each report. My thinking is we can expand the interface to this funciton if we ever wan't configurable sorting. Also adds a sorting interface 'CookbookRecordsByName' in reporting/cookbooks.go for CookbookRecords keeping that logic encasulated with the type.
Signed-off-by: Jon Morrow <jmorrow@chef.io>
Fixes #98

Implements sorting on cookbooks report #98

---

cmd/capture.go
cmd/errors.go
cmd/root.go
go.mod
go.sum
pkg/reporting/capture.go
pkg/reporting/capture_test.go
pkg/reporting/client.go
pkg/reporting/client_test.go
pkg/reporting/object_writer.go
pkg/reporting/object_writer_test.go
vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/modules.txt

This adds an initial `capture` command to `chef analyze`.
`chef analyze capture`  accepts a node as an argument and creates a chef repo
that contains:
* node object
* required cookbooks
* roles
* environments
This scope of this change extends to creating and populating the chef repository,
but does not include configuring a node.
closes chef/chef-workstation#1017

Adds "chef analyze capture NODE"

---

cmd/capture.go
pkg/reporting/capture.go
pkg/reporting/capture_test.go
pkg/reporting/object_writer.go
pkg/reporting/object_writer_test.go

In order to test against the captured node, it's necessary
to generate a kitchen.yml configuration appropriate for the node.
This change adds the generation of a kitchen.yml
as the last step of node capture. Currently it looks
at node attributes to determine the type of image to create,
but this is limited to platform-name+platform-version (eg ubuntu-18.04)
This is suitable for our initial set of cases, but we will need to add
more flexibility in determining the right image name and the provider
(currently always vagrant), and will need to add prompting in cases
where we can't determine the correct provider/image.

Generate a kitchen.yml as part of capture

---

pkg/reporting/chef_client.go
pkg/reporting/chef_client_test.go
pkg/reporting/setup_test.go

The credentials file is documented as being able to have the client key inlined as a TOML heredoc. go-libs correctly reads the heredoc; however, the current chef-analyze code assumes that the value read is always the path to a file. This change simply looks for the RSA header, and if present, assumes the key has been inlined.
Fixes https://github.com/chef/go-libs/issues/11

Allow inlining literal client_key in credentials

---

cmd/capture.go
cmd/errors.go
cmd/infra_flags.go
cmd/report.go
cmd/root.go
integration/featflag_test.go
integration/help_test.go
main.go

1. Adds support for the chef-server/infra related flags (like --chef-server-url) to the `capture` command by moving it to be shared across report and capture. 
2. Cleans up minor inconsistencies in flag names (dash instead of underscore)
3. Adds integration tests for help output of capture, report nodes, report cookbooks. 
4. Moves long feature flag disabled error message into `cmd/error`. Minor corrections to the text. Gave it its very own error number. 
closes #239

Make infra flags common to report and capture sub commands

---

cmd/report.go
cmd/root.go
cmd/session.go
cmd/upload.go
integration/help_test.go
pkg/dist/global.go

This updates descriptions and usage text to reflect
the new entry point of 'chef report', 'chef capture' instead of
'chef-analyze'.
This includes an alias for `upload` so that it can be accessed from
the `chef` invocation `chef report upload` -> `chef-analyze upload`,
and render the correct usage text.
Text corrections have also been made for clarity and consistency with other
CLI tool conventions.

Support use as `chef report` and `chef capture`

---

cmd/capture.go
cmd/text.go

Smoothes some wording in the capture cookbook location loop, mainly by being a lot more verbose - which could be good or bad, depending on perspective.  I've added a "Press Enter to Continue" prompt to keep instructions from scrolling off prior to displaying the cookbook list, which is of unpredictable length.
I stopped short of adding color, because doing so can't really be done in plain text (you really need a function, because you need to detect platform, then decide what to do) and that would involve changing how this whole area of code works. We could add asterisks or something, if more emphasis is wanted.
Sample run:
```
- Setting up local repository
- Capturing node object 'node-01'
- Capturing cookbooks...
- Capturing environment...
- Capturing roles...
- Writing kitchen …
```

capture: several small UI tweaks

---

.buildkite/hooks/post-artifact

Having a significant part of the full report showing up as comments
in PR was making it difficult to navigate feedback and comments

Post just the % change and link in the PR coverage report comment

---

cmd/capture.go
cmd/text.go
pkg/reporting/capture.go
pkg/reporting/capture_test.go
pkg/reporting/client_test.go
pkg/reporting/cookbooks.go
pkg/reporting/object_writer.go
pkg/reporting/object_writer_test.go

This adds chef-capture support for policy-managed nodes.
It works in the same way that it does for non-policy-managed nodes -
it will capture the node's state and dependencies (in this case - policy group/policy/cookbook
artifacts) from a Chef Infra Server, and saves it into a local 'captured node' repository 
where it's served up on test-kitchen VM via chef-zero. 
This differs from running policyfile tests in TK in that Kitchen itself won't attempt to
resolve or download any cookbook dependencies - it relies on chef capture having captured the complete node state, including policy/artifacts applied  into the node repo before kitchen converge.
This functionality relies on a new provisioner for TK, "chef_zero_capture". This
provisioner ships with chef-cli, and is now available in 3.0.4+ of …

Policyfile capture support

---

.studiorc

This is not a supported arch for any OS. And with golang 15.1 it's
giving us build errors on darwin/386, which is now unsupported.

Drop i386 from hab studio build

---

pkg/formatter/csv_test.go
pkg/formatter/txt_test.go
pkg/reporting/cookstyle.go
pkg/reporting/cookstyle_test.go

Cookstyle 7.0 changed the format due to upstream RuboCop changes.
Signed-off-by: Tim Smith <tsmith@chef.io>

Update to work with the new Cookstyle naming format
