.bldr.toml

Build the right habitat package

---

.expeditor/verify.pipeline.yml

I might have copy/paste this label...

Update buildkite verify label

---

.expeditor/verify.pipeline.yml
.studiorc
go.mod
go.sum
pkg/config/config.go
pkg/config/config_test.go

Adds 84.2% test coverage to 'config' Go package

---

.expeditor/config.yml
.expeditor/coverage.pipeline.yml
.expeditor/update_coverage.sh
.expeditor/upload_coverage.sh

Implement chaining actions when a workflow is completed

---

.expeditor/config.yml

Change workflow chaining for buildkite events

---

.expeditor/config.yml
.expeditor/update_coverage.sh

Last Try! Use merge actions plus buildkit event

---

.expeditor/update_coverage.sh

Fix unbound variable at .expeditor/update_converge

---

.buildkite/hooks/post-artifact

This PR is just shrinking the table inside the Github Comment that the pipeline posts.
**Example Before:** https://github.com/chef/chef-analyze/pull/53#issuecomment-549699438
**Example After:** https://github.com/chef/chef-analyze/pull/54#issuecomment-550013668
N/A

[pipeline] Shrink Code Coverage Table (GH Comment)

---

.expeditor/build.habitat.yml

Follow up from https://github.com/chef/chef-analyze/pull/64
Gotta pass the environment variable to the pipeline!

Pass CI=true to habitat build pipeline

---

.studiorc

Install git for downloading go deps

---

pkg/reporting/client_test.go
pkg/reporting/cookbooks.go
pkg/reporting/cookbooks_test.go
pkg/reporting/nodes_test.go

Adding more coverage for the cookbook file.
N/A

Adding further unit test coverage

---

pkg/formatter/csv_test.go
pkg/formatter/table.go
pkg/formatter/table_test.go
pkg/formatter/txt_test.go

Somehow we ended up printing the report twice.
Output:
```
$ chef-analyze report nodes
Node Name      Chef Version   Operating System    Cookbooks
-----------------+--------------+-------------------+------------
bar              -              -                   -
chef-load-6      13.2.28        mac_os_x v10.14.6   -
chef-load-40     12.5.54        mac_os_x v10.14.6   -
kitchen-ubuntu   15.3.14        ubuntu v18.04       -
chef-load-52     13.1.0         ubuntu v18.04       -
chef-load-7      15.3.14        platform 14 v       -
chef-load-9      15.3.14        ubuntu v18.04       -
chef-load-8      15.3.14        windows v6.3.9600   -
chef-load-50     15.3.14        platform 14 v       -
chef-load-4      15.3.14        windows v6.3.9600   -
ubuntu-node1     15.3.14        ubuntu v18.04 …
```

nodes-report:(bug) double printing report

---

cmd/report.go

Use CSV ext for CSV files

---

pkg/formatter/csv_test.go

Add tests for csv formatter

---

go.sum

One of the old dependencies is failing our Windows builds for some reason.

Tidying up old Golang dependencies

---

.bldr.toml
habitat/plan.ps1
habitat/plan.sh
scripts/integration_tests.ps1

Build Habitat packages for Windows systems.
Closes .https://github.com/chef/chef-analyze/issues/35

hab:(exe) build packages for Windows

---

cmd/report.go
pkg/formatter/csv.go
pkg/formatter/csv_test.go
pkg/formatter/table.go
pkg/formatter/table_test.go
pkg/formatter/txt.go
pkg/formatter/txt_test.go
pkg/reporting/cookbooks.go
pkg/reporting/cookbooks_test.go
pkg/reporting/nodes.go
pkg/reporting/nodes_test.go

Add --node-filter support for cookbook/node reports

---

pkg/formatter/table_test.go

Increase coverage: add test for filter footer in report

---

pkg/formatter/csv.go
pkg/formatter/csv_test.go
pkg/formatter/formatter.go
pkg/formatter/formatter_internal_test.go
pkg/formatter/table.go
pkg/formatter/table_test.go
pkg/formatter/txt.go
pkg/formatter/txt_test.go
pkg/reporting/cookbooks.go
pkg/reporting/cookbooks_test.go
pkg/reporting/nodes.go
pkg/reporting/nodes_test.go

Fixes https://github.com/chef/chef-analyze/issues/97

Adding sorting logic to the Node report

---

.expeditor/verify.pipeline.yml

This should fix our failing windows tests.
Signed-off-by: Tim Smith <tsmith@chef.io>

Update how we run the Windows tests

---

.expeditor/verify.pipeline.yml

Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>

Explicitly define expeditor secrets account name

---

.expeditor/config.yml

Update expeditor configuration

---

.buildkite/hooks/post-artifact

Signed-off-by: Vikram Karve <vikram.karve@progress.com>
Addresses comment in https://github.com/chef/chef-analyze/pull/576

Update env variable to reflect new default branch name
